services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    working_dir: /app
    command: npm run dev
    container_name: foodie-backend
    ports:
      - "5001:5000"
      - "9229:9229"

    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=foodie-db
      - DB_PORT=5432
      - DB_SSL=false
      - DOCKERIZED=true
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./postgres/.env
    networks:
      - foodie-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: foodie-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # 내 코드(src, package.json)를 컨테이너에 연결
      - /app/node_modules # node_modules는 내 컴퓨터가 아닌 Docker 컨테이너 안에서만 관리
    depends_on:
      - backend
    networks:
      - foodie-net

  postgres:
    image: postgres:15
    container_name: foodie-db
    restart: always
    env_file:
      - ./postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jiyoung -d foodie"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - foodie-net

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    env_file:
      - ./stripe/.env
    command: >
      listen
      --device-name local-docker
      --forward-to backend:5000/api/stripe/webhook
    depends_on:
      - backend
    networks:
      - foodie-net

  stripe-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    working_dir: /app
    command: npm run worker
    container_name: foodie-stripe-worker
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=foodie-db
      - DB_PORT=5432
      - DB_SSL=false
      - DOCKERIZED=true
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./postgres/.env
    networks:
      - foodie-net

volumes:
  pgdata:

networks:
  foodie-net:
    driver: bridge
